displayName=ChatBet
author=Vira X Vespa
description=Thieving pickpocket tracker + odds/probability calculator for elf pickpocketing (integrates with XP Tracker goals)
tags=thieving,pickpocket,probability,odds,tracker,stream
version=
plugins=com.vxv.chatbet.ChatBetPlugin
build=standard